### ISSUE TITLE
crash when prettyprinting Mock() in ipython

### ISSUE THREAD

**Issue by anntzer** [tommikaikkonen/prettyprinter#61]
* PrettyPrinter version: 0.17
* Python version: 3.7
* Operating System: linux

### Description

Trying to prettyprint a unittest.mock.Mock in ipython causes a crash.

### What I Did

```
In [1]: unittest.mock.Mock()                                                                                        
Out[1]: /home/antony/.local/lib/python3.7/site-packages/prettyprinter/prettyprinter.py:343: UserWarning: The pretty printer for Mock, prettyprinter.prettyprinter._repr_pretty, raised an exception. Falling back to default repr.

Traceback (most recent call last):
  File "/home/antony/.local/lib/python3.7/site-packages/prettyprinter/prettyprinter.py", line 383, in _run_pretty
    doc = pretty_fn(value, ctx)
  File "/home/antony/.local/lib/python3.7/site-packages/prettyprinter/prettyprinter.py", line 420, in _repr_pretty
    return fn(value, ctx)
  File "/home/antony/.local/lib/python3.7/site-packages/prettyprinter/extras/ipython_repr_pretty.py", line 119, in pretty_repr_pretty
    unbound_repr_pretty = value._repr_pretty_.__func__
  File "/home/antony/miniconda3/lib/python3.7/unittest/mock.py", line 592, in __getattr__
    raise AttributeError(name)
AttributeError: __func__

  UserWarning
<Mock id='140143210872448'>

In [2]:
```

Interestingly enough, things seem to work fine when directly calling cpprint from a regular console:
```
>>> from prettyprinter import cpprint; from unittest.mock import Mock
>>> cpprint(Mock())
<Mock id='139690004808592'>
```

**Comment by tommikaikkonen** [comment]
Fixed in 0.18.0
